package blendinLetter;

import java.util.Scanner;

public class Interface {
	
	String comando;

	public static void main(String[] args) {
		Decodify translate = new Decodify();
		Scanner read = new Scanner(System.in);
		translate.setCode("DTÁ, QMHEME I EPJRP! \nSFCV É S TAMAHAC. MFXGJ DVZWCLB RG PVB HW 1883, T MFGGCLV IKHI PEJII \nAE WHXRVSCÇI DYW JU QMS RPRKMT IGÉ ZGRÊA. (CIYJMV IKHI VHWXI QS XXTZI \n'NDTGEFSW ASNPURRLT XNVS D XNWKPLB 3', IDT É WOVAVIGÓVAD XNVS RIYSMGWF HS \nPKNHWBQN HG IMZTG). KWPÊW HGWIENTTZIFIM GIE BCVXSH XRVYJVGEK, T LRTGXA QSK \nPKBRLTKVQWCBBW VD MFXJPVUEYTLBR, UPZN, IM CÃW PYDEW ISUÊH! \n\nMAXÃG D YHI SRWAXWRMH JGX QFWG: SMCSAH LB KDDJAEJ, TC IMJTQ PLSRWGE HDZ GIJ \nEMEHASW HQS QIGEDWI QI YAIQMSSWEIK EIEE VJIF GJXIAÇEK. PXRWSG LR XWG ZRGMEMEEVD \nURY LGIOEDWW (ZYAIW TVSIW CSJ XAFS, ACKYYKXDR), QWJA PSDTONW GUKVEAH KBRLXVHEJPU \nZI UWIZEFSW CSJ PXRPASWF QSALBWGH. IGÉ S HGÓXEMG QMOÊ HG IMZTG BM PLSBIIE VT \nJYEFSQA WWB IZMYDA! ISUÊH ANFWB W DYW É KQIIJ PAFME? \n\nTVDYSCBB IM TAGENP XRRKPVQS WB KBQG TC QEJXI GYVD XNVS HME VWHXRMLPLB \nTWAW OITÊ SW GIEEW, HQ UPZN IKFCVWAIW RQ XDZZE VT BEMSCOHPG PXNVWRMH RGH \nURYK HWALGH M QMKHM DYW EWQMS VIEEFIQE UMT W OITÊ SW GIEEW AYFRI ZEAH \nUR MFRWZSVPZVE. LJLB UMT MH TJTKVWSKI SERTZ RVS PXRVLPZ FYS BÃW! AYFRI SYA \nBCVXG QWZ IE IWZEJ SMPMKÕTA FST EZRWKÃD, M OIE, D ZRWLD DBGÊK HIOIE! FCNRVD \nIPSJSMV EIJMYI LGQNRYJTB IKICCMVD BVRZP CFEVD W ZIM RWETG EIEE NXIWEJ CW GIEEW \nR HWHBEYAG W HRAKMEWG XVGIAGW R ELÉ D JRFÊ VD BRQHD! \n\nXBV KDZGI, G QMOÊ HG IMZTG CÃW RWLÁ TFNXSBMAXW... BWEXG. KIV PWKIE QAA \nIASK EIEE SH AHEK BWYIUJTNW KT ZRGGCAGMLJQEIE, T YHEFSW VWKD IPSFIMPIJ, TTR \nZSX NVGSG UHMLD MZFMGZNHG DA NKWCBRW VD BRQHD BNQTÉB ABFJTDVZWGIZ, TGXA \nFÓ QSCLNQ HGWWIÇÕWH PBPGVZNJARIF RSH UVWKÕTA CIJXOBWSH. UNW G AWYTZ T W \nQYFSOEIF UQPEJPU SYJXWFSK RWZ S IJM RY XXH! \n\nAELJZNPETVGI, AHAB WAVVVJARI DYW TAGÁ EUDVGIUTVQS MBI PEÇSSI \nVRLTZQMETVFMGCIY GGB ITIFIMF XWCBNRVD UR PGRIYMRPZ CEJP YHI WJ ARNS ECAMVD. \nUNW XDQ GYVD CZ QSA-MAXWCLVHG. \n\nP ÚTGMEP KBMKP YHI WJ YHIJD É QE TSGIE RS RIQIAP, MAXÃG BM RWUDVQM FD \nXNWKPLB. JGX LVZWGBVHG EWE YE IMZTG KME E HPQFEYTU, PSFKMEWSG KBQ XXOHVSH \nPVWLÓGQPEK, KQFMLPZ B EFDA 50 R EHGMAHWG I QEFÇPZ GAAHB.(GSJRQ B XGGVBDWAW \nR JAFCRM KTU NRVPZ CSJ JUN WWBIAE). \n\nWJ YHIJXI PSFWMPIJ D DRPZD WRWLT BNQTÉB, UNW IJIAHG UCV TSGI YÁ EHPZRGA \nPKVHWCBNPETVGI FP NEIFIM QI MB BEIE T UVRZP NVXS SW GIEEW FI HPZGMM TU \n50 CIVPÇWF.(EUWW DYW D BEIE EWQI LTZ FEÍVD LBW LGQYLGH. MFTWGW DYW XAFS FÃD \nMAXJT XNVS P PVWLÓGQN!). \n\nHW IWQE XDZZE, KÓ FCRVAP LVDWG XNVS CÃW FI HGMBGMEIEIE RWZMYD! RÁ \nPSFHMTYA BM RRLJZZEJ RWZ E HDXHPSÇÃD, M PSFHMTYA JU RQHGMTS UDVPIJIIAHG \nGMYÓKADA QI TDTFS. LPUOÉQ UDVGVSX CZE VDMAÇE HDXHPSG LN ÉTGRI QE UDZEMVP LB \nSMGW, RWLDC NHGGIAHG IWQE WHAN RGHBNPYXI! BFJXONHG EWE XGSI N EBJLN, I KT IYKMB \nITIFIM QS LTUCS NXME TJDKHVSG XBV EXU, QMYP I RPWH YHI NDKÊF RÃG HIOIE SM AEVP!\n\nJYIFSQA FDTVWEEXV OPSCLVR, 1883");
		//Há um erro no nome Blendin, quando se fala no Blendin Sem Amigos tem um "a" ao invés de um "e", na palavra triângulo está faltando acentuação, no entanto, esse são erros do livro, não do algoritmo.
		translate.setKeyword("PINES");
		translate.keywordTextGenerator();
		translate.formula();
		System.out.println(translate.getText());
	}
}